export const organizationData = [
  {
    id: 1,
    name: "Tech Solutions",
    key: "TS",
    owner: "Muhammad Ali",
    ownerAvatar: "https://i.pravatar.cc/40?img=11",
    email: "info@techsolutions.com",
    phone: "+92 300 1234567",
    website: "https://techsolutions.com",
    description: "Enterprise Software Development Company",
    members: 25,
    projects: 12,
    workspaces: 3,
    status: "Active",
    createdAt: "2026-08-01",
  },

  {
    id: 2,
    name: "Future Systems",
    key: "FS",
    owner: "Sarah Khan",
    ownerAvatar: "https://i.pravatar.cc/40?img=5",
    email: "hello@future.com",
    phone: "+92 301 1111111",
    website: "https://future.com",
    description: "Cloud Infrastructure & DevOps",
    members: 18,
    projects: 8,
    workspaces: 2,
    status: "Active",
    createdAt: "2026-08-05",
  },

  {
    id: 3,
    name: "NextGen AI",
    key: "NGAI",
    owner: "Ahmed Raza",
    ownerAvatar: "https://i.pravatar.cc/40?img=14",
    email: "admin@nextgen.ai",
    phone: "+92 302 2222222",
    website: "https://nextgen.ai",
    description: "Artificial Intelligence Company",
    members: 40,
    projects: 21,
    workspaces: 5,
    status: "Planning",
    createdAt: "2026-08-10",
  },

  {
    id: 4,
    name: "Creative Studio",
    key: "CS",
    owner: "Fatima Noor",
    ownerAvatar: "https://i.pravatar.cc/40?img=9",
    email: "contact@creative.com",
    phone: "+92 333 5555555",
    website: "https://creative.com",
    description: "Design & Branding Agency",
    members: 15,
    projects: 9,
    workspaces: 2,
    status: "Completed",
    createdAt: "2026-07-18",
  },
];