export const backlogIssues = [
  {
    id: "ATL-1",
    title: "Onboarding Experience",
    description: "Improve the onboarding flow for new users.",
    type: "Task",
    priority: "High",
    status: "To Do",
    dueDate: "2026-08-11",
    sprint: "Backlog",
    assignee: {
      id: "u1",
      name: "Ayesha Khan",
      initials: "AK",
    },
    reporter: {
      id: "u2",
      name: "Daniel Ross",
      initials: "DR",
    },
    labels: ["onboarding", "frontend"],
    storyPoints: 5,
    epic: "User Experience",
  },

  {
    id: "ATL-2",
    title: "Billing & Payments",
    description: "Implement billing and payment management.",
    type: "Story",
    priority: "Highest",
    status: "In Progress",
    dueDate: "2026-08-12",
    sprint: "Backlog",
    assignee: {
      id: "u2",
      name: "Daniel Ross",
      initials: "DR",
    },
    reporter: {
      id: "u1",
      name: "Ayesha Khan",
      initials: "AK",
    },
    labels: ["billing", "backend"],
    storyPoints: 8,
    epic: "Payments",
  },

  {
    id: "ATL-100",
    title: "Implement OAuth sign-in",
    description: "Add Google and GitHub OAuth authentication.",
    type: "Story",
    priority: "High",
    status: "To Do",
    dueDate: "2026-08-14",
    sprint: "Backlog",
    assignee: {
      id: "u3",
      name: "Mei Lin",
      initials: "ML",
    },
    reporter: {
      id: "u1",
      name: "Ayesha Khan",
      initials: "AK",
    },
    labels: ["authentication"],
    storyPoints: 5,
    epic: "Authentication",
  },

  {
    id: "ATL-101",
    title: "Fix cart total rounding",
    description: "Correct rounding issues in cart calculations.",
    type: "Bug",
    priority: "Highest",
    status: "To Do",
    dueDate: "2026-08-15",
    sprint: "Backlog",
    assignee: {
      id: "u4",
      name: "Omar Farouk",
      initials: "OF",
    },
    reporter: {
      id: "u2",
      name: "Daniel Ross",
      initials: "DR",
    },
    labels: ["bug", "checkout"],
    storyPoints: 3,
    epic: "Checkout",
  },

  {
    id: "ATL-102",
    title: "Create onboarding checklist",
    description: "Create a checklist for new users.",
    type: "Story",
    priority: "Medium",
    status: "In Progress",
    dueDate: "2026-08-16",
    sprint: "ATL Sprint 13",
    assignee: {
      id: "u1",
      name: "Ayesha Khan",
      initials: "AK",
    },
    reporter: {
      id: "u3",
      name: "Mei Lin",
      initials: "ML",
    },
    labels: ["onboarding"],
    storyPoints: 5,
    epic: "User Experience",
  },

  {
    id: "ATL-103",
    title: "Add dark mode tokens",
    description: "Add reusable design tokens for dark mode.",
    type: "Task",
    priority: "Low",
    status: "Testing",
    dueDate: "2026-08-18",
    sprint: "ATL Sprint 13",
    assignee: {
      id: "u3",
      name: "Mei Lin",
      initials: "ML",
    },
    reporter: {
      id: "u1",
      name: "Ayesha Khan",
      initials: "AK",
    },
    labels: ["design", "frontend"],
    storyPoints: 3,
    epic: "Design System",
  },

  {
    id: "ATL-104",
    title: "Improve dashboard load time",
    description: "Optimize dashboard performance and API calls.",
    type: "Improvement",
    priority: "Medium",
    status: "Done",
    dueDate: "2026-08-20",
    sprint: "ATL Sprint 13",
    assignee: {
      id: "u5",
      name: "Daniel Noor",
      initials: "DN",
    },
    reporter: {
      id: "u2",
      name: "Daniel Ross",
      initials: "DR",
    },
    labels: ["performance"],
    storyPoints: 5,
    epic: "Performance",
  },

  {
    id: "ATL-105",
    title: "Write E2E tests for checkout",
    description: "Cover checkout flow with end-to-end tests.",
    type: "Story",
    priority: "High",
    status: "Backlog",
    dueDate: "2026-08-22",
    sprint: "Backlog",
    assignee: {
      id: "u6",
      name: "John Williams",
      initials: "JW",
    },
    reporter: {
      id: "u1",
      name: "Ayesha Khan",
      initials: "AK",
    },
    labels: ["testing", "checkout"],
    storyPoints: 8,
    epic: "Checkout",
  },
];