export const workspaceMembersData = {
  1: [
    {
      id: 1,
      name: "Muhammad Ali",
      username: "muhammad",
      email: "muhammad@example.com",
      avatar: "https://i.pravatar.cc/100?img=11",
      role: "Admin",
      status: "Active",
    },
    {
      id: 2,
      name: "Sarah Khan",
      username: "sarah",
      email: "sarah@example.com",
      avatar: "https://i.pravatar.cc/100?img=5",
      role: "Member",
      status: "Active",
    },
    {
      id: 3,
      name: "Ahmed Raza",
      username: "ahmed",
      email: "ahmed@example.com",
      avatar: "https://i.pravatar.cc/100?img=14",
      role: "Member",
      status: "Active",
    },
    {
      id: 4,
      name: "Fatima Noor",
      username: "fatima",
      email: "fatima@example.com",
      avatar: "https://i.pravatar.cc/100?img=9",
      role: "Viewer",
      status: "Active",
    },
  ],

  2: [
    {
      id: 5,
      name: "Sarah Khan",
      username: "sarah",
      email: "sarah@example.com",
      avatar: "https://i.pravatar.cc/100?img=5",
      role: "Admin",
      status: "Active",
    },
    {
      id: 6,
      name: "Bilal Ahmed",
      username: "bilal",
      email: "bilal@example.com",
      avatar: "https://i.pravatar.cc/100?img=12",
      role: "Member",
      status: "Active",
    },
  ],

  3: [
    {
      id: 7,
      name: "Ahmed Raza",
      username: "ahmed",
      email: "ahmed@example.com",
      avatar: "https://i.pravatar.cc/100?img=14",
      role: "Admin",
      status: "Active",
    },
    {
      id: 8,
      name: "Ayesha Malik",
      username: "ayesha",
      email: "ayesha@example.com",
      avatar: "https://i.pravatar.cc/100?img=20",
      role: "Member",
      status: "Active",
    },
    {
      id: 9,
      name: "Usman Tariq",
      username: "usman",
      email: "usman@example.com",
      avatar: "https://i.pravatar.cc/100?img=13",
      role: "Viewer",
      status: "Active",
    },
  ],
};